import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://lhppyzpqjtsjzrjlpkoi.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxocHB5enBxanRzanpyamxwa29pIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODU5ODk0MywiZXhwIjoyMDk0MTc0OTQzfQ.X_Uhsjp3D982McNtWHb14KGl6OiEYiUDGEA3NukEM6g'
)

// source mapping from HubSpot "Original Traffic Source" column
// referrer URL used to distinguish organic social platforms
// bing/yahoo/ecosia organic → 'other'
// AI Referrals → 'other'
// Referrals → 'referral'

const leads = [
  // Page 1
  { name: 'Bob', address: 'Lyne', lead_source: 'direct' },
  { name: 'William Duff', address: 'Guildford', lead_source: 'google' },
  { name: 'James Austin', address: 'Chertsey', lead_source: 'direct' },
  { name: 'Liam Stansfield', address: 'Retford', lead_source: 'direct' },
  { name: 'Dominic Brooks', address: 'Hale', lead_source: 'google_organic' },
  { name: 'John Keast', address: 'Epsom', lead_source: 'direct' },
  { name: 'Chris Gill', address: 'Redhill', lead_source: 'direct' },
  { name: 'Roisin Coyle', address: 'Addlestone', lead_source: 'google_organic' },
  { name: 'Kelly Wimble', address: 'West Horsley', lead_source: 'google_organic' },
  { name: 'Narvind Singh', address: 'Epsom', lead_source: 'direct' },
  { name: 'Eri Horrocks', address: 'Guildford', lead_source: 'direct' },
  { name: 'Sharon Falcon', address: 'London', lead_source: 'direct' },
  { name: 'Oliver Watson', address: 'Esher', lead_source: 'google' },
  { name: 'Ella Flora', lead_source: 'direct' },
  { name: 'Andrew Ronay', address: 'Ottershaw', lead_source: 'direct' },
  { name: 'Chris Bancroft', address: 'London', lead_source: 'google_organic' },
  { name: 'Matt Bowden', address: 'Worcester Park', lead_source: 'google' },
  { name: 'Annie Fnn', address: 'Sunbury', lead_source: 'google_organic' },
  { name: 'David Napier', address: 'Woking', lead_source: 'google_organic' },
  { name: 'Sepehr Miremadi', address: 'Walton-on-Thames', lead_source: 'google' },
  { name: 'Thea Rodgers', address: 'Shepperton', lead_source: 'google_organic' },
  { name: 'Francesca Elliott', address: 'Alton', lead_source: 'google_organic' },
  { name: 'Baz Mistry', address: 'Uxbridge', lead_source: 'google_organic' },
  { name: 'Jack Foster', address: 'Camberley', lead_source: 'google_organic' },
  { name: 'Jessica Kennedy', lead_source: 'direct' },
  { name: 'David Demetriou', address: 'Cornwall', lead_source: 'google_organic' },
  { name: "Deborah O'Dea", address: 'Surrey', lead_source: 'direct' },
  { name: 'Harriet Mundy', address: 'Guildford', lead_source: 'direct' },
  // Page 2
  { name: 'Lynne Gamble', address: 'Gracehill', lead_source: 'google_organic' },
  { name: 'Jo Reynoldson-Kim', address: 'Ashtead', lead_source: 'google' },
  { name: 'Diane Novis', address: 'Surrey', lead_source: 'google' },
  { name: 'Louis', address: 'Epsom', lead_source: 'google_organic' },
  { name: 'Martin Baxter', lead_source: 'google_organic' },
  { name: 'Mark Botkai', address: 'London', lead_source: 'google_organic' },
  { name: 'Ben', address: 'Worthing', lead_source: 'google_organic' },
  { name: 'Ameer Ali', address: 'Dagenham', lead_source: 'direct' },
  { name: 'Charlotte Heard', address: 'Chertsey', lead_source: 'google_organic' },
  { name: 'Henry Davies', address: 'London', lead_source: 'direct' },
  { name: 'Helen Murphy', address: 'Woking', lead_source: 'google_organic' },
  { name: 'Javier Haboba', address: 'Guildford', lead_source: 'google' },
  { name: 'Jasmin Wing', address: 'Berkshire', lead_source: 'direct' },
  { name: 'Michael Elliott', address: 'Southampton', lead_source: 'google_organic' },
  { name: 'Sharaz', address: 'Woking', lead_source: 'google_organic' },
  { name: 'Nikolay Zhekov', address: 'Chertsey', lead_source: 'google_organic' },
  { name: 'Katherine Clowser', address: 'Guildford', lead_source: 'direct' },
  { name: 'David Bullen', address: 'Camberley', lead_source: 'direct' },
  { name: 'Jack Clayton', address: 'Burgess Hill', lead_source: 'google' },
  { name: 'Tim Boxall', address: 'Guildford', lead_source: 'google_organic' },
  { name: 'James', address: 'New Malden', lead_source: 'google_organic' },
  { name: 'Zelkin Lo', address: 'Woking', lead_source: 'referral' },
  { name: 'Jessica Reid', address: 'New Malden', lead_source: 'google_organic' },
  { name: 'Zoe Gardiner', address: 'Newdigate', lead_source: 'google_organic' },
  { name: 'Ollie', address: 'Reigate', lead_source: 'instagram' },
  { name: 'Deborah Bettinson', address: 'Staines', lead_source: 'direct' },
  { name: 'Matt Ruby', address: 'Chertsey', lead_source: 'instagram' },
  { name: 'Nealon Francois', address: 'London', lead_source: 'google_organic' },
  { name: 'Ruby Sbeyk', address: 'Addlestone', lead_source: 'google' },
  { name: 'Lewis Hill', address: 'Wickford', lead_source: 'direct' },
  // Page 3
  { name: 'Ricky Cabrera', address: 'Surrey', lead_source: 'google' },
  { name: 'T Marshall', address: 'Surbiton', lead_source: 'direct' },
  { name: 'Karan Kapoor', address: 'Bracknell', lead_source: 'google' },
  { name: 'Jonathan Mayne', lead_source: 'google_organic' },
  { name: 'Jefferson', address: 'Surrey', lead_source: 'instagram' },
  { name: 'Mohamad Farid', address: 'Surrey', lead_source: 'direct' },
  { name: 'Timothy Speight', address: 'Walton-on-Thames', lead_source: 'google' },
  { name: 'Nick Horsley', address: 'Hollingbourne', lead_source: 'direct' },
  { name: 'Kristina Franklin', lead_source: 'google_organic' },
  { name: 'Scott Newman', lead_source: 'google_organic' },
  { name: 'Heather Smith', address: 'Redhill', lead_source: 'google_organic' },
  { name: 'Marie Newman', address: 'Ashtead', lead_source: 'direct' },
  { name: 'Mike Perrelle', address: 'Guildford', lead_source: 'direct' },
  { name: 'Jen Beatts', address: 'Bury St Edmunds', lead_source: 'google_organic' },
  { name: 'Louiza', address: 'Hemel Hempstead', lead_source: 'facebook' },
  { name: 'Sam Wood', address: 'Thames Ditton', lead_source: 'google_organic' },
  { name: 'Michelle Heywood', address: 'Windsor', lead_source: 'google_organic' },
  { name: 'Vish', lead_source: 'google' },
  { name: 'Chris Pattison', address: 'Esher', lead_source: 'google' },
  { name: 'Oliver Smith', address: 'Old Woking', lead_source: 'google' },
  { name: 'Azita-Maria Rushton', address: 'Redhill', lead_source: 'google' },
  { name: 'Tiffany Howkins', address: 'Egham', lead_source: 'direct' },
  { name: 'Simon McIlwaine', address: 'Sutton', lead_source: 'google_organic' },
  { name: 'Adrian Beavis', address: 'Woking', lead_source: 'google' },
  { name: 'Sarah Hind', address: 'Virginia Water', lead_source: 'google_organic' },
  { name: 'James Gardiner', address: 'Newdigate', lead_source: 'google_organic' },
  { name: 'Karen Megranahan', address: 'Esher', lead_source: 'direct' },
  { name: 'Sandeep Sharma', address: 'Cambridge', lead_source: 'other' },
  // Page 4
  { name: 'Carrie Fouche', lead_source: 'direct' },
  { name: 'Guadalupe Bribiesca', address: 'Camberley', lead_source: 'direct' },
  { name: 'Kevin Johnston', address: 'Walton-on-Thames', lead_source: 'instagram' },
  { name: 'Mark Sherwin', address: 'Church Crookham', lead_source: 'google_organic' },
  { name: 'Daniel Thomson', address: 'East Molesey', lead_source: 'google' },
  { name: 'Mark Sanders', address: 'Poole', lead_source: 'direct' },
  { name: 'Gavin Morris', lead_source: 'google_organic' },
  { name: 'Adam Walsh', address: 'Surbiton', lead_source: 'google_organic' },
  { name: 'Anahaad Sultani', address: 'Ashford', lead_source: 'direct' },
  { name: 'Callum Cowx', lead_source: 'google' },
  { name: 'Sarah Bokaie', address: 'London', lead_source: 'google_organic' },
  { name: 'Martin Collins', address: 'Aldridge', lead_source: 'direct' },
  { name: 'Jamie Hugill', lead_source: 'google_organic' },
  { name: 'Mo Rahman', address: 'Farnham', lead_source: 'google_organic' },
  { name: 'Rolf Martens', address: 'Thames Ditton', lead_source: 'google' },
  { name: 'Ashley Ross', address: 'Bracknell', lead_source: 'google' },
  { name: 'Lisa Parker', address: 'Kilmarnock', lead_source: 'google_organic' },
  { name: 'Geoff Harris', address: 'Crowthorne', lead_source: 'google' },
  { name: 'Steven Dalton', address: 'Bracknell', lead_source: 'google_organic' },
  { name: 'Tom Robson', lead_source: 'google' },
  { name: 'Charlie Evagorou', address: 'Surrey', lead_source: 'direct' },
  { name: 'Micah Gonzales', address: 'Leander', lead_source: 'google_organic' },
  { name: 'Andrew Towers Roberts', address: 'Tarbert', lead_source: 'direct' },
  { name: 'Diane Shoults', address: 'Buxton', lead_source: 'google_organic' },
  { name: 'Bob', address: 'Manchester', lead_source: 'direct' },
  { name: 'Alex', address: 'East Grinstead', lead_source: 'other' },
  { name: 'Sophie Bairstow', address: 'Ascot', lead_source: 'direct' },
  { name: 'Bridget Dowling', address: 'Hampton', lead_source: 'instagram' },
  // Page 5
  { name: 'Joanne Cross', address: 'Shepperton', lead_source: 'direct' },
  { name: 'Jasmin Sandhu', address: 'Windsor', lead_source: 'direct' },
  { name: 'Maria Flemmer', address: 'London', lead_source: 'direct' },
  { name: 'Joanne Morris', address: 'Worcester Park', lead_source: 'google' },
  { name: 'Langden Batt', lead_source: 'direct' },
  { name: 'Les Mumboirs', address: 'Kingston upon Thames', lead_source: 'direct' },
  { name: 'Jordan Brackenbury-Cox', address: 'Woking', lead_source: 'google_organic' },
  { name: 'Kevin McGuinness', address: 'Worcester Park', lead_source: 'google' },
  { name: 'Mat Kelly', address: 'Huntingdon', lead_source: 'google_organic' },
  { name: 'Andrew Bartlett', address: 'Sandbach', lead_source: 'google_organic' },
  { name: 'N Nattress', address: 'Doncaster', lead_source: 'google_organic' },
  { name: 'George Quixley', address: 'Guildford', lead_source: 'direct' },
  { name: 'Isabel', address: 'Hook', lead_source: 'direct' },
  { name: 'Caner Anac', address: 'Farnham', lead_source: 'direct' },
  { name: 'Karin', address: 'Bexley', lead_source: 'direct' },
  { name: 'John Ostins', address: 'Bristol', lead_source: 'direct' },
  { name: 'Rob Gypps', address: 'Dunmow', lead_source: 'direct' },
  { name: 'Jamie Hale', address: 'Guildford', lead_source: 'direct' },
  { name: 'Mark Sawyer', address: 'Hemel Hempstead', lead_source: 'direct' },
  { name: 'Leila Rodwell', address: 'Thames Ditton', lead_source: 'direct' },
  { name: 'Dominic Searle', lead_source: 'direct' },
  { name: 'Brett Stevenson', address: 'Kenilworth', lead_source: 'direct' },
  { name: 'Mike de la Perrelle', address: 'Guildford', lead_source: 'direct' },
  { name: 'Natalia Lenart', address: 'Godalming', lead_source: 'direct' },
  { name: 'Justin Hewitt-Coleman', address: 'Woking', lead_source: 'direct' },
  { name: 'Denis Naberezhnykh', address: 'Addlestone', lead_source: 'direct' },
  // Page 6
  { name: 'Josh Sanders', address: 'Isleworth', lead_source: 'direct' },
  { name: 'Helen Richardson', address: 'Wakefield', lead_source: 'other' },
  { name: 'Tony Downes', address: 'Conwy', lead_source: 'direct' },
  { name: 'Matt Pope', address: 'St Albans', lead_source: 'direct' },
  { name: 'Shona Allerton', address: 'Caterham', lead_source: 'direct' },
  { name: 'Nicola Sayer', address: 'Nottingham', lead_source: 'other' },
  { name: 'Luke Hamilton', address: 'Surbiton', lead_source: 'direct' },
  { name: 'Brinda Assi', address: 'Kent', lead_source: 'direct' },
  { name: 'Jacqui G', address: 'Farnham', lead_source: 'direct' },
  { name: 'Cheryl Finn', address: 'Salisbury', lead_source: 'direct' },
  { name: 'Warwick Rosekilly', address: 'Weybridge', lead_source: 'direct' },
  { name: 'David', address: 'Farnham', lead_source: 'google_organic' },
  { name: 'Coralie Estrade', address: 'Cheltenham', lead_source: 'direct' },
  { name: 'Claire Hill', address: 'Crowthorne', lead_source: 'google' },
  { name: 'Paul Snook', address: 'Crawley', lead_source: 'direct' },
  { name: 'Laura Smythies', address: 'Manchester', lead_source: 'google_organic' },
  { name: 'Chris Alder', address: 'Wokingham', lead_source: 'google' },
  { name: 'Francis Burke', address: 'Brentwood', lead_source: 'google_organic' },
  { name: 'Guy Edwards', address: 'Staines', lead_source: 'google' },
  { name: 'James', address: 'Much Wenlock', lead_source: 'google_organic' },
  { name: 'Nikolaos Nitsas', address: 'Surrey', lead_source: 'google' },
  { name: 'Sam Margrave', address: 'Bedworth', lead_source: 'google_organic' },
  { name: 'Caroline Quirk', address: 'Southampton', lead_source: 'direct' },
  { name: 'Richard Hockley', address: 'Windsor', lead_source: 'direct' },
  { name: 'Danny McClean', address: 'Waterlooville', lead_source: 'google' },
  { name: 'Gary Eccles', address: 'Middlesbrough', lead_source: 'google_organic' },
  { name: 'Kim Davies', address: 'West Molesey', lead_source: 'direct' },
  { name: 'Thomas Wetton', address: 'Mickleover', lead_source: 'google_organic' },
  { name: 'Danielle Hargreaves', address: 'Hyndburn', lead_source: 'direct' },
  // Page 7
  { name: 'Amelie', address: 'Birmingham', lead_source: 'google' },
  { name: 'Sam Storrar', address: 'Ascot', lead_source: 'direct' },
  { name: 'Philip Jones', address: 'Addlestone', lead_source: 'google' },
  { name: 'David Yung', address: 'Ascot', lead_source: 'direct' },
  { name: 'Ben Parkinson', address: 'Thames Ditton', lead_source: 'other' },
  { name: 'Matt Griffiths', address: 'Yateley', lead_source: 'direct' },
  { name: 'Amy Evans', address: 'New Haw', lead_source: 'direct' },
  { name: 'Andrea Tut', address: 'Bracknell', lead_source: 'google' },
  { name: 'Tee Robins', address: 'Thames Ditton', lead_source: 'direct' },
  { name: 'Jessica Orchard', address: 'Farnham', lead_source: 'other' },
  { name: 'Will', address: 'Godalming', lead_source: 'instagram' },
  { name: 'Andrew Turnbull', address: 'Godalming', lead_source: 'direct' },
  { name: 'William Jeffries', address: 'Twickenham', lead_source: 'other' },
  { name: 'G Dhaliwal', address: 'Solihull', lead_source: 'other' },
  { name: 'Peter Brathwaite', address: 'Bedford', lead_source: 'google_organic' },
  { name: 'Alex', address: 'Molesey', lead_source: 'direct' },
  { name: 'Donna Dowson', address: 'Walton-on-Thames', lead_source: 'direct' },
  { name: 'Robert Stace', address: 'West Byfleet', lead_source: 'google' },
  { name: 'Jack Speller', address: 'Surrey', lead_source: 'direct' },
  { name: 'Patricia Cogram', lead_source: 'direct' },
  { name: 'Nathan Murray', address: 'London', lead_source: 'direct' },
  { name: 'Alison Susans', address: 'Bexleyheath', lead_source: 'google_organic' },
  { name: 'Kate Hilton', address: 'Windsor', lead_source: 'direct' },
  { name: 'Summer Rams', address: 'Berkshire', lead_source: 'direct' },
  { name: 'Freddie Mack', address: 'Headley Down', lead_source: 'direct' },
  { name: 'John Peverall', address: 'Addlestone', lead_source: 'direct' },
  { name: 'Lloyd Watters', address: 'Cobham', lead_source: 'google' },
  { name: 'Joshua Halsey', address: 'Camberley', lead_source: 'other' },
  { name: 'Sheum Wan', address: 'Radlett', lead_source: 'direct' },
  // Page 8
  { name: 'Pippa Elms', address: 'Godalming', lead_source: 'direct' },
  { name: 'Timothy Bull', address: 'Walton-on-Thames', lead_source: 'other' },
  { name: 'Jack Collins', address: 'Ashford', lead_source: 'direct' },
  { name: 'Sharan Sangha', lead_source: 'direct' },
  { name: 'Edward Baxter', address: 'West Byfleet', lead_source: 'google' },
  { name: 'Kerem Sahin', address: 'Thames Ditton', lead_source: 'direct' },
  { name: 'Gustavo Ribeiro', address: 'Woking', lead_source: 'facebook' },
  { name: 'Paddy Martin', address: 'Uttoxeter', lead_source: 'direct' },
  { name: 'Richard Barnes', address: 'Wokingham', lead_source: 'direct' },
  { name: 'Sukh', address: 'Reading', lead_source: 'direct' },
  { name: 'Eby Jacob', address: 'Chertsey', lead_source: 'google' },
  { name: 'Paul Wakeman', address: 'Reading', lead_source: 'google_organic' },
  { name: 'Chloe Irving', address: 'Isle of Man', lead_source: 'direct' },
  { name: 'Charles Cross', address: 'Leatherhead', lead_source: 'direct' },
  { name: 'Tiny', address: 'Sheffield', lead_source: 'direct' },
  { name: 'Debbie Coles', address: 'Camberley', lead_source: 'direct' },
  { name: 'Louise Young', address: 'Windlesham', lead_source: 'direct' },
  { name: 'Karolina Kielbowicz', address: 'Staines', lead_source: 'google_organic' },
  { name: 'Nick Cousins', address: 'New Malden', lead_source: 'google_organic' },
  { name: 'Robert Jenkins', address: 'Worcester Park', lead_source: 'google' },
  { name: 'Scott Golding', lead_source: 'direct' },
  { name: 'Mary Watt', address: 'Surbiton', lead_source: 'google_organic' },
  { name: 'Karen Coles', address: 'Ascot', lead_source: 'direct' },
  { name: 'Pippo', address: 'Ashford', lead_source: 'direct' },
  { name: 'Simon Clarkson', address: 'Lytham St Annes', lead_source: 'other' },
  { name: 'Matt Dobson', address: 'Addlestone', lead_source: 'direct' },
  { name: 'Paul Rogers', address: 'Surbiton', lead_source: 'google_organic' },
  { name: 'Rob Poore', address: 'Walton-on-Thames', lead_source: 'direct' },
  { name: 'Gem B', address: 'Aldershot', lead_source: 'direct' },
  // Page 9
  { name: "Laura O'Connor", address: 'Feltham', lead_source: 'direct' },
  { name: 'Eilish Jamieson', address: 'Esher', lead_source: 'other' },
  { name: 'Tom Herring', lead_source: 'direct' },
  { name: 'Carol', address: 'Reigate', lead_source: 'direct' },
  { name: 'Marcus Doyle', address: 'Lancing', lead_source: 'direct' },
  { name: 'Marina Braganza', address: 'Shepperton', lead_source: 'direct' },
  { name: 'Jessica Ellis', address: 'Teddington', lead_source: 'google' },
  { name: 'Zoe', address: 'East Molesey', lead_source: 'direct' },
  { name: 'Rachel Jones', address: 'Bergerac', lead_source: 'direct' },
  { name: 'Jacob Tyler-White', address: 'Guildford', lead_source: 'direct' },
  { name: 'Liezl Wentworth', address: 'Weybridge', lead_source: 'google' },
  { name: 'Neil Hetherington', address: 'St Leonards on Sea', lead_source: 'google_organic' },
  { name: 'Jennifer Richmond', address: 'Chertsey', lead_source: 'google' },
  { name: 'Bob', address: 'London', lead_source: 'direct' },
  { name: 'Ajay Rajput', address: 'Feltham', lead_source: 'google' },
  { name: 'Jordan Moon', address: 'Caerphilly', lead_source: 'google_organic' },
  { name: 'Michael Koopowitz', address: 'Ascot', lead_source: 'google_organic' },
  { name: 'Jack M', address: 'Manchester', lead_source: 'direct' },
  { name: 'Ehsheveh', address: 'London', lead_source: 'direct' },
  { name: 'Marie', address: 'Chichester', lead_source: 'direct' },
  { name: 'Jamie', address: 'Epsom', lead_source: 'direct' },
  { name: 'Jeff Jeffson', address: 'London', lead_source: 'direct' },
  { name: 'Paul Kingman', address: 'London', lead_source: 'direct' },
  { name: 'Nathan Wilgoss', address: 'Epsom', lead_source: 'direct' },
  { name: 'Jonathan Elsmore', address: 'Guildford', lead_source: 'google_organic' },
  { name: 'Richard', address: 'Leatherhead', lead_source: 'direct' },
  { name: 'Edward Wiesztort', address: 'Surrey', lead_source: 'google' },
  // Page 10
  { name: 'Keigan Docherty', address: 'Camberley', lead_source: 'google' },
  { name: 'Jon', address: 'Leamington', lead_source: 'direct' },
  { name: 'Luke', address: 'Aldershot', lead_source: 'direct' },
  { name: 'Greg Wakelin', address: 'Ottershaw', lead_source: 'google' },
  { name: 'Sinead Griksas', address: 'Gilford', lead_source: 'direct' },
  { name: 'Andrew King', address: 'Woking', lead_source: 'google' },
  { name: 'James Jones', address: 'Wokingham', lead_source: 'direct' },
  { name: 'George Joyce', address: 'Ashtead', lead_source: 'direct' },
  { name: 'Jane Kew', address: 'Worcester Park', lead_source: 'direct' },
  { name: 'Tom Mellish', address: 'Hersham', lead_source: 'google_organic' },
  { name: 'Julie Davies', address: 'Shepperton', lead_source: 'google' },
  { name: 'John Ashcroft', address: 'Busveal', lead_source: 'google' },
  { name: 'Dylan Morgan', address: 'Haslemere', lead_source: 'direct' },
  { name: 'Erin', address: 'Harlow', lead_source: 'direct' },
  { name: 'Ronny', address: 'London', lead_source: 'google_organic' },
  { name: 'John Barnes', address: 'Guildford', lead_source: 'direct' },
  { name: 'Will White', address: 'Hardwick', lead_source: 'google_organic' },
  { name: 'Melissa Henson', address: 'Cobham', lead_source: 'google_organic' },
  { name: 'Vincenzo Scafuto', address: 'Brock Hill', lead_source: 'google' },
  { name: 'Maria', address: 'Staines', lead_source: 'google' },
  { name: 'Stefan Baran', address: 'Twickenham', lead_source: 'google_organic' },
  { name: 'Natasha Spokes', address: 'Leighton Buzzard', lead_source: 'direct' },
  { name: 'Angus Kearin', address: 'Chigwell', lead_source: 'direct' },
  { name: 'Steven Bacci', address: 'Englefield Green', lead_source: 'direct' },
  { name: 'James Richardson', address: 'Runnymede', lead_source: 'direct' },
  { name: 'Jo Hall', lead_source: 'direct' },
  { name: 'Darren Flack', address: 'Stansted Mountfitchet', lead_source: 'referral' },
  { name: 'Nicola Borowiec', address: 'Carshalton', lead_source: 'direct' },
  // Page 11
  { name: 'Barry Ivens', address: 'Worcester Park', lead_source: 'google' },
  { name: 'Richard Childs', address: 'Colchester', lead_source: 'direct' },
  { name: 'Daniel Wilding', address: 'Yapton', lead_source: 'direct' },
  { name: 'Adam Williams', lead_source: 'direct' },
  { name: 'Umesh Kalra', address: 'Calne', lead_source: 'direct' },
  { name: 'Jamie', address: 'Woking', lead_source: 'direct' },
  { name: 'Caroline', address: 'Guildford', lead_source: 'google_organic' },
  { name: 'Neil Saunders', address: 'Windsor', lead_source: 'google' },
  { name: 'Verity Taylor', lead_source: 'direct' },
  { name: 'Kathryn Jones', address: 'St Albans', lead_source: 'google_organic' },
  { name: 'Richard Hile', address: 'Ilkeston', lead_source: 'direct' },
  { name: 'Jason Townshend', address: 'Great Bookham', lead_source: 'direct' },
  { name: 'Paul Farrer', address: 'London', lead_source: 'direct' },
  { name: 'Diletta Ponchielli', address: 'Woking', lead_source: 'google_organic' },
  { name: 'John Smith', address: 'London', lead_source: 'other' },
  { name: 'Tim Shelley', address: 'Reigate', lead_source: 'direct' },
  { name: 'Jason Gill', address: 'Iver', lead_source: 'direct' },
  { name: 'Sara Rassouli', address: 'Twickenham', lead_source: 'direct' },
  { name: 'Chris Ehinger', address: 'Windsor', lead_source: 'google' },
  { name: 'Molly Breeden', address: 'Addlestone', lead_source: 'facebook' },
  { name: 'Francesca Lavelle', address: 'Windsor', lead_source: 'direct' },
  { name: 'Kate West', address: 'Great Yarmouth', lead_source: 'google_organic' },
  { name: 'Tegan McCaslin', address: 'Oxford', lead_source: 'google_organic' },
  { name: 'Laura Sheehy', address: 'Virginia Water', lead_source: 'direct' },
  { name: 'Heidi Gomes', address: 'New Malden', lead_source: 'direct' },
  { name: 'Jennie Conway', address: 'Egham', lead_source: 'google' },
  { name: 'Tom Chapman', lead_source: 'google_organic' },
  // Page 12
  { name: 'Melanie Ditschun', address: 'Peasmarsh', lead_source: 'direct' },
  { name: 'Stuart McKay', address: 'Surrey', lead_source: 'direct' },
  { name: 'Shahid Naqvi', address: 'Manchester', lead_source: 'google_organic' },
  { name: 'Lou Rich', lead_source: 'google' },
  { name: 'Mike Jones', address: 'West Byfleet', lead_source: 'direct' },
  { name: 'Mohamedjaffer', address: 'Stanmore', lead_source: 'direct' },
  { name: 'Liam Quinn', address: 'West Molesey', lead_source: 'google' },
  { name: 'Michael Balabukh', address: 'Ealing', lead_source: 'direct' },
  { name: 'Claudia Beaney', address: 'Bracknell', lead_source: 'direct' },
  { name: 'Steve Thompson', address: 'Walton-on-Thames', lead_source: 'direct' },
  { name: 'John MacBrayne', address: 'Surrey', lead_source: 'google_organic' },
  { name: 'Jazz Bhalla', address: 'Egham', lead_source: 'direct' },
  { name: 'Michelina Loggia', address: 'Surrey', lead_source: 'instagram' },
  { name: 'Patrick Harding', address: 'Amersham', lead_source: 'direct' },
  { name: 'Melissa Boyd', address: 'London', lead_source: 'direct' },
  { name: 'Emma Pym', address: 'Camberley', lead_source: 'direct' },
  { name: 'Stanley Greening', address: 'Toddington', lead_source: 'direct' },
  { name: 'Michael Stone', address: 'Egham', lead_source: 'google' },
  { name: 'Anna Holmes', address: 'Guilden Morden', lead_source: 'google_organic' },
  { name: 'Sophie Barua', address: 'Thames Ditton', lead_source: 'google' },
  { name: 'Andrew Brown', address: 'Farnham', lead_source: 'direct' },
  { name: 'Iain Stewart', address: 'London', lead_source: 'google_organic' },
  { name: 'Ruth Higginson', address: 'Earith', lead_source: 'google_organic' },
  { name: 'Andy Wildy', lead_source: 'google_organic' },
  { name: 'Kyle Houldsworth', address: 'Morpeth', lead_source: 'google_organic' },
  { name: 'Bob', address: 'Addlestone', lead_source: 'google' },
  { name: 'Halina Klos', address: 'London', lead_source: 'google_organic' },
  { name: 'Joe George', address: 'Spelthorne', lead_source: 'google' },
  { name: 'Peter Prior', address: 'Runnymede', lead_source: 'direct' },
  // Page 13
  { name: 'Naseer Kannambath', address: 'Ashford', lead_source: 'google' },
  { name: 'Helen', address: 'London', lead_source: 'direct' },
  { name: 'Josh Higginson', address: 'Coulsdon', lead_source: 'google' },
  { name: 'David Clarke', address: 'Hampton', lead_source: 'google' },
  { name: 'Sarah Wilson', address: 'Teddington', lead_source: 'direct' },
  { name: 'Jack Crowe', address: 'Ascot', lead_source: 'other' },
  { name: 'Ben West', address: 'Woking', lead_source: 'direct' },
  { name: 'Jo Norfolk', address: 'Guildford', lead_source: 'google_organic' },
  { name: 'Karl Kjelstrup-Johnson', address: 'London', lead_source: 'direct' },
  { name: 'Sam', address: 'Worcester Park', lead_source: 'google_organic' },
  { name: 'Maria Watson', lead_source: 'direct' },
  { name: 'Rebecca Wilding', address: 'Feltham', lead_source: 'google' },
  { name: 'Bib Squirek', address: 'Romney', lead_source: 'google' },
  { name: 'Bryony Symons', address: 'Woking', lead_source: 'google_organic' },
  { name: 'Duncan Humphrey', address: 'Woking', lead_source: 'google' },
  { name: 'Matt Day', address: 'Maidenhead', lead_source: 'direct' },
  { name: 'Simon Rutter', address: 'Basingstoke', lead_source: 'google_organic' },
  { name: 'Laura Browne', address: 'Worcester Park', lead_source: 'direct' },
  { name: 'Fiona Larkin', address: 'London', lead_source: 'google' },
  { name: 'Dave Taylor', address: 'Basingstoke', lead_source: 'google' },
  { name: 'Nicola Majekodunmi', address: 'New Malden', lead_source: 'direct' },
  { name: 'Paul Griffiths', address: 'Windlesham', lead_source: 'google' },
  { name: 'Tina Manchu', address: 'Leicester', lead_source: 'google_organic' },
  { name: 'Joe', address: 'Camberley', lead_source: 'google' },
  { name: 'John Reardon', address: 'Surbiton', lead_source: 'google' },
  { name: 'Ben Gibbs', address: 'Sheffield', lead_source: 'google_organic' },
  { name: 'Paul Greatbatch', address: 'Hersham', lead_source: 'google' },
  { name: 'Alice Foster', address: 'Southampton', lead_source: 'google' },
  { name: 'Ian Meadows', address: 'Ascot', lead_source: 'google' },
  // Page 14
  { name: 'Nicky Penn', address: 'Chertsey', lead_source: 'direct' },
  { name: 'Jonathan Long', address: 'Bramley', lead_source: 'direct' },
  { name: 'Jamila Karim', address: 'Kenley', lead_source: 'google' },
  { name: 'Dave', address: 'Woking', lead_source: 'direct' },
  { name: 'Lucy Masson', address: 'Godalming', lead_source: 'direct' },
  { name: 'Claire Taylor', address: 'Richmond', lead_source: 'direct' },
  { name: 'Tom Hobc', address: 'East Molesey', lead_source: 'google' },
  { name: 'Parag Bhambure', address: 'Maidenhead', lead_source: 'google_organic' },
  { name: 'Aidin', address: 'Staines', lead_source: 'direct' },
  { name: 'Andy Nouri', address: 'Camberley', lead_source: 'google_organic' },
  { name: 'Rajesh Puri', address: 'London', lead_source: 'direct' },
  { name: 'Alison Batten', address: 'Isleworth', lead_source: 'google' },
  { name: 'David Norden', address: 'Berkhamsted', lead_source: 'direct' },
  { name: 'Mathew Melvin', address: 'Walton-on-Thames', lead_source: 'google' },
  { name: 'Peter Skardelli', address: 'New Haw', lead_source: 'direct' },
  { name: 'Irma Robles', address: 'Weybridge', lead_source: 'google_organic' },
  { name: 'Lola Laseinde', address: 'London', lead_source: 'direct' },
  { name: 'Luke Farrington', address: 'London', lead_source: 'google_organic' },
  { name: 'Shrey', address: 'Gorakhpur', lead_source: 'direct' },
  { name: 'Johannes Wiese', address: 'Freiburg', lead_source: 'google_organic' },
  { name: 'Gabriel Reynard-Antoniou', address: 'Ware', lead_source: 'google_organic' },
  { name: 'Luke Smith', address: 'Wimbledon', lead_source: 'direct' },
  { name: 'Helen Brown', address: 'Walton-on-Thames', lead_source: 'google' },
  { name: 'Andrew Ferguson', address: 'Ash Green', lead_source: 'other' },
  // Page 15
  { name: 'Matthieu Light', address: 'Woking', lead_source: 'google_organic' },
  { name: 'Raksha Keshwala', address: 'Bracknell', lead_source: 'direct' },
  { name: 'Ben Turner', address: 'Epsom', lead_source: 'direct' },
  { name: 'Jaswinder Dosanjh', address: 'Chertsey', lead_source: 'direct' },
  { name: 'Joe Whelan', address: 'Godalming', lead_source: 'direct' },
  { name: 'Kate Hardesty', address: 'Virginia Water', lead_source: 'direct' },
  { name: 'Danny N', address: 'Walton-on-Thames', lead_source: 'google_organic' },
  { name: 'Lucy Thomas', address: 'Byfleet', lead_source: 'facebook' },
  { name: 'Phoebe Niven', address: 'Weybridge', lead_source: 'facebook' },
  { name: 'Katy Morgan', address: 'Sharpthorne', lead_source: 'google' },
  { name: 'Daniel Simms', address: 'Bexleyheath', lead_source: 'google_organic' },
  { name: 'Kya Hulme', address: 'Godalming', lead_source: 'direct' },
  { name: 'Jane Russell', address: 'Aldershot', lead_source: 'google' },
  { name: 'Ross Kelly', address: 'Kingston upon Thames', lead_source: 'google' },
  { name: 'Gemma Clarke', address: 'Worcester Park', lead_source: 'google' },
  { name: 'Laura McNamara', address: 'Walton-on-Thames', lead_source: 'facebook' },
  { name: 'James Coulson', address: 'Surbiton', lead_source: 'direct' },
  { name: 'Rob', address: 'Staines upon Thames', lead_source: 'google_organic' },
  { name: 'Ryan Midgley', address: 'Guildford', lead_source: 'direct' },
  { name: 'Paige Norris', address: 'Leatherhead', lead_source: 'google' },
  { name: 'S Smith', address: 'Bracknell', lead_source: 'direct' },
  { name: 'Gary Cleaver', address: 'Swindon', lead_source: 'google' },
  { name: 'Osama Abushama', address: 'Dublin', lead_source: 'google_organic' },
  { name: 'Andrew Clarkson', lead_source: 'direct' },
  { name: 'Carys Doyle', address: 'Morden', lead_source: 'direct' },
  { name: 'Reece', address: 'Bristol', lead_source: 'direct' },
  // Page 16
  { name: 'Neil Gallamore', lead_source: 'google' },
  { name: 'Emma Roberts', lead_source: 'direct' },
  { name: 'Carl Staniforth', address: 'Godalming', lead_source: 'direct' },
  { name: 'Dan Nutbeen', address: 'Aldershot', lead_source: 'google' },
  { name: 'Gemma Garand', address: 'Walton-on-Thames', lead_source: 'facebook' },
  { name: 'Nicole', address: 'Guildford', lead_source: 'google_organic' },
  { name: 'Graham Beynon', address: 'Cambridge', lead_source: 'direct' },
  { name: 'Tracey Ayer', address: 'Virginia Water', lead_source: 'direct' },
  { name: 'Rob Carter', address: 'Sunderland', lead_source: 'direct' },
  { name: 'Caroline', address: 'Teddington', lead_source: 'direct' },
  { name: 'Alastair Bloore', address: 'Ashtead', lead_source: 'google_organic' },
  { name: 'Andy Latchford', address: 'Walton-on-Thames', lead_source: 'direct' },
  { name: 'Anita Pecsi', address: 'Woking', lead_source: 'google' },
  { name: 'Chaz Vilkhu', address: 'Burnham', lead_source: 'instagram' },
  { name: 'Tracy', address: 'Staines', lead_source: 'direct' },
  { name: 'Lucy Teixeira', lead_source: 'google_organic' },
  { name: 'Beckie Mulkerrins', address: 'Farnborough', lead_source: 'google' },
  { name: 'Markus', address: 'London', lead_source: 'direct' },
  { name: 'Jason', address: 'Egham', lead_source: 'direct' },
  { name: 'Emma Russell', address: 'Godalming', lead_source: 'direct' },
  { name: 'Steve Smith', address: 'Cottenham', lead_source: 'direct' },
  { name: 'Raghvir Dhaliwal', address: 'Runnymede', lead_source: 'google' },
  { name: 'Maurice Fitzgerald', address: 'Worcester Park', lead_source: 'google' },
  { name: 'Callum Tanner', address: 'London', lead_source: 'google_organic' },
  { name: 'Stoyan Genov', address: 'Walton-on-Thames', lead_source: 'direct' },
  { name: 'Kimberly Williams', address: 'Albany', lead_source: 'direct' },
  // Page 17
  { name: 'Nikolaos Pardalis', address: 'Guildford', lead_source: 'direct' },
  { name: 'Sarah Lulham', address: 'Epsom', lead_source: 'google' },
  { name: 'Howard Graham', address: 'London', lead_source: 'google_organic' },
  { name: 'Jai Range', address: 'Surbiton', lead_source: 'google' },
  { name: "Katherine O'Connor", address: 'Surbiton', lead_source: 'google_organic' },
]

async function run() {
  const rows = leads.map(l => ({
    name: l.name,
    address: l.address ?? null,
    lead_source: l.lead_source,
    stage: 'new_lead',
    pipeline: 'sales',
    is_hot: false,
    tags: [],
  }))

  // Insert in batches of 50
  const batchSize = 50
  let inserted = 0
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize)
    const { error } = await supabase.from('leads').insert(batch)
    if (error) {
      console.error(`Batch ${i / batchSize + 1} error:`, error.message)
    } else {
      inserted += batch.length
      console.log(`Inserted batch ${i / batchSize + 1} (${inserted}/${rows.length})`)
    }
  }
  console.log(`Done. ${inserted} leads imported.`)
}

run().catch(console.error)
